spring:
  datasource:
    username: codelex
    password: codelex
    url: jdbc:postgresql://localhost:5432/group-dinner
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/updates.xml
  queries:


security:
  basic: enabled=false
